module.exports = {
    'Mensaje de error al crear la oferta sin título': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .windowMaximize()
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "")
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .pause(1500)
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "El titulo: \"\" es inválido, el título no puede estar vacío")
        .pause(1500)
    },

    'Mensaje de error al crear la oferta sin requerimientos especiales': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador de software")
        .setValue("#requerimientosEspeciales","")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#codPostal", "1011")
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .pause(1500)
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "Los requerimientos especiales no pueden estar vacíos")
        .pause(1500)
    },

    'Mensaje de error al crear la oferta sin vacante': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#requerimientosEspeciales","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#codPostal", "1011")
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .pause(1500)
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "La cantidad de vacantes: es inválida, no puede estar vacía")
        .pause(1500)
    },

    'Mensaje de error al crear la oferta con vacante negativa': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#requerimientosEspeciales","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#vacantes", "-1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#codPostal", "1011")
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .pause(1500)
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "La cantidad de vacantes: -1 es inválida, debe ser mayor a cero")
        .pause(1500)
    },

    'Mensaje de error al crear la oferta con duración negativa': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#requerimientosEspeciales","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "-8")
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#codPostal", "1011")
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .pause(1500)
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "Las horas totales: -8 no pueden ser menores a 0")
        .pause(1500)
    },

    'Mensaje de error al crear la oferta con monto de remuneración negativo': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#requerimientosEspeciales","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")
        .setValue("#monto", "-700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#codPostal", "1011")
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .pause(1500)
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "El monto: -700 es inválido, no puede ser negativo")
        .pause(1500)
    },

    'Mensaje de error al crear la oferta con dirección sin calle 1': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#requerimientosEspeciales","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")
        .setValue("#monto", "700")
        .setValue("#calle1", "")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#codPostal", "1011")
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .pause(1500)
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "La calle1: es inválida, no puede estar vacía")
        .pause(1500)
    },

    'Mensaje de error al crear la oferta con dirección sin calle 2': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#requerimientosEspeciales","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#codPostal", "1011")
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .pause(1500)
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "La calle2: es inválida, no puede estar vacía")
        .pause(1500)
    },

    'Mensaje de error al crear la oferta con dirección sin ciudad': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#requerimientosEspeciales","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "")
        .setValue("#estado", "Distrito Capital")
        .setValue("#codPostal", "1011")
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .pause(1500)
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "La ciudad: es inválida, no puede estar vacía")
        .pause(1500)
    },

    'Mensaje de error al crear la oferta con dirección sin estado': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#requerimientosEspeciales","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "")
        .setValue("#codPostal", "1011")
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .pause(1500)
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "El estado: es inválido, no puede estar vacío")
        .pause(1500)
    },

    'Mensaje de error al crear la oferta con dirección sin codigo postal': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#requerimientosEspeciales","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#codPostal", "")
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .pause(1500)
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "El código postal: es inválido, no puede estar vacío")
        .pause(1500)
    },
    'Creación de oferta': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#requerimientosEspeciales","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-10-10")
        .setValue("#duracion", "8")
        .setValue("#monto", "7")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#codPostal", "1011")
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(6) > div:nth-child(2) > button")
        .setValue("#fechaCalendario", "2020-08-08")
        .setValue("#horaInicio", "15:00:00")
        .setValue("#horaFin", "18:00:00")
        .click("#agregarCalendario")
        .click("#aceptarCalendario")
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .pause(1500)
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "Oferta Creada Con éxito")
        .pause(1500)
    },

    'Consultar Ofertas': function(browser){
        browser.url("http://localhost:8087/oferta")
        .assert.containsText("#app > div.v-application--wrap > main > div > div > div > div > div > div > div.py-4.ma-sm-9.v-card.v-sheet.v-sheet--shaped.theme--light.elevation-4 > div.v-data-table.mt-5.mx-5.v-data-table--fixed-header.v-data-table--has-bottom.theme--light > div.v-data-table__wrapper > table > tbody > tr:nth-child(1) > td:nth-child(1)", "Desarrollador")
        .assert.containsText("#app > div.v-application--wrap > main > div > div > div > div > div > div > div.py-4.ma-sm-9.v-card.v-sheet.v-sheet--shaped.theme--light.elevation-4 > div.v-data-table.mt-5.mx-5.v-data-table--fixed-header.v-data-table--has-bottom.theme--light > div.v-data-table__wrapper > table > tbody > tr:nth-child(1) > td:nth-child(2)", "2020-10-10")
        .assert.containsText("#app > div.v-application--wrap > main > div > div > div > div > div > div > div.py-4.ma-sm-9.v-card.v-sheet.v-sheet--shaped.theme--light.elevation-4 > div.v-data-table.mt-5.mx-5.v-data-table--fixed-header.v-data-table--has-bottom.theme--light > div.v-data-table__wrapper > table > tbody > tr:nth-child(1) > td:nth-child(3)", "Creada")
        .assert.containsText("#app > div.v-application--wrap > main > div > div > div > div > div > div > div.py-4.ma-sm-9.v-card.v-sheet.v-sheet--shaped.theme--light.elevation-4 > div.v-data-table.mt-5.mx-5.v-data-table--fixed-header.v-data-table--has-bottom.theme--light > div.v-data-table__wrapper > table > tbody > tr:nth-child(1) > td:nth-child(4) > span", "8 horas")
        .assert.containsText("#app > div.v-application--wrap > main > div > div > div > div > div > div > div.py-4.ma-sm-9.v-card.v-sheet.v-sheet--shaped.theme--light.elevation-4 > div.v-data-table.mt-5.mx-5.v-data-table--fixed-header.v-data-table--has-bottom.theme--light > div.v-data-table__wrapper > table > tbody > tr:nth-child(1) > td:nth-child(5)", "$ 7 por hora")
        .pause(2000)
    },

    'Publicar Oferta': function(browser){
        browser.url("http://localhost:8087/oferta")
        .click("#app > div.v-application--wrap > main > div > div > div > div > div > div > div.py-4.ma-sm-9.v-card.v-sheet.v-sheet--shaped.theme--light.elevation-4 > div.v-data-table.mt-5.mx-5.v-data-table--fixed-header.v-data-table--has-bottom.theme--light > div.v-data-table__wrapper > table > tbody > tr:nth-child(1) > td:nth-child(6) > button.v-icon.notranslate.v-icon--link.v-icon--dense.mdi.mdi-clipboard-check.theme--light.green--text")
        .assert.containsText("#app > div.v-application--wrap > main > div > div > div > div > div > div > div.v-snack.v-snack--active.v-snack--has-background.v-snack--top > div > div.v-snack__content", "Oferta publicada con éxito")
        .pause(2000)
    }
}
