module.exports = {
    'Mensaje de error al crear la oferta sin título': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "")
        .setValue("#descripcion","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#cargo", "Desarrollador Web Junior")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")  
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#zip", "1011")
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-6 > div > div.v-input__control > div.v-input__slot > div.v-select__slot > div.v-select__selections")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active")
        .pause(500)
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-3 > div > div.v-input__control > div.v-input__slot")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active") 
        .pause(500)
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "El titulo: \"\" es inválido, el título no puede estar vacío")
        .pause(2000)
    },

    'Mensaje de error al crear la oferta sin descripción': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#descripcion","")
        .setValue("#cargo", "Desarrollador Web Junior")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")  
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#zip", "1011")
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-6 > div > div.v-input__control > div.v-input__slot > div.v-select__slot > div.v-select__selections")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active")
        .pause(500)
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-3 > div > div.v-input__control > div.v-input__slot")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active") 
        .pause(500)
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "La descripcion: es inválida, la descripcion no puede estar vacía")
        .pause(2000)
    },

    'Mensaje de error al crear la oferta sin cargo': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#descripcion","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#cargo", "")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")  
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#zip", "1011")
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-6 > div > div.v-input__control > div.v-input__slot > div.v-select__slot > div.v-select__selections")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active")
        .pause(500)
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-3 > div > div.v-input__control > div.v-input__slot")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active") 
        .pause(500)
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "El cargo: \"\" es inválido, el cargo no puede estar vacío")
        .pause(2000)
    },

    'Mensaje de error al crear la oferta sin vacante': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#descripcion","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#cargo", "Desarrollador Web Junior")
        .setValue("#vacantes", "")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")  
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#zip", "1011")
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-6 > div > div.v-input__control > div.v-input__slot > div.v-select__slot > div.v-select__selections")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active")
        .pause(500)
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-3 > div > div.v-input__control > div.v-input__slot")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active") 
        .pause(500)
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "La cantidad de vacantes: es inválida, no puede estar vacía")
        .pause(2000)
    },

    'Mensaje de error al crear la oferta con vacante negativa': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#descripcion","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#cargo", "Desarrollador Web Junior")
        .setValue("#vacantes", "-1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")  
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#zip", "1011")
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-6 > div > div.v-input__control > div.v-input__slot > div.v-select__slot > div.v-select__selections")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active")
        .pause(500)
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-3 > div > div.v-input__control > div.v-input__slot")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active") 
        .pause(500)
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "La cantidad de vacantes: -1 es inválida, debe ser mayor a cero")
        .pause(2000)
    },

    'Mensaje de error al crear la oferta con duración negativa': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#descripcion","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#cargo", "Desarrollador Web Junior")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "-8")  
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#zip", "1011")
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-6 > div > div.v-input__control > div.v-input__slot > div.v-select__slot > div.v-select__selections")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active")
        .pause(500)
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-3 > div > div.v-input__control > div.v-input__slot")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active") 
        .pause(500)
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "Las horas totales: -8 no pueden ser menores a 0")
        .pause(2000)
    },

    'Mensaje de error al crear la oferta sin frecuencia de remuneración': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#descripcion","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#cargo", "Desarrollador Web Junior")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")  
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#zip", "1011")
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-3 > div > div.v-input__control > div.v-input__slot")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active") 
        .pause(500)
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "La frecuencia de pago: es inválida, no puede estar vacía")
        .pause(2000)
    },

    'Mensaje de error al crear la oferta con monto de remuneración negativo': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#descripcion","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#cargo", "Desarrollador Web Junior")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")  
        .setValue("#monto", "-700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#zip", "1011")
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-6 > div > div.v-input__control > div.v-input__slot > div.v-select__slot > div.v-select__selections")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active")
        .pause(500)
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-3 > div > div.v-input__control > div.v-input__slot")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active") 
        .pause(500)
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "El monto: -700 es inválido, no puede ser negativo")
        .pause(2000)
    },

    'Mensaje de error al crear la oferta sin divisa de remuneración': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#descripcion","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#cargo", "Desarrollador Web Junior")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")  
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#zip", "1011")
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-6 > div > div.v-input__control > div.v-input__slot > div.v-select__slot > div.v-select__selections")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active")
        .pause(500)
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "La divisa del pago: es inválida, no puede estar vacía")
        .pause(2000)
    },

    'Mensaje de error al crear la oferta con dirección sin calle 1': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#descripcion","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#cargo", "Desarrollador Web Junior")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")  
        .setValue("#monto", "700")
        .setValue("#calle1", "")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#zip", "1011")
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-6 > div > div.v-input__control > div.v-input__slot > div.v-select__slot > div.v-select__selections")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active")
        .pause(500)
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-3 > div > div.v-input__control > div.v-input__slot")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active") 
        .pause(500)
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "La calle1: es inválida, no puede estar vacía")
        .pause(2000)
    },

    'Mensaje de error al crear la oferta con dirección sin calle 2': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#descripcion","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#cargo", "Desarrollador Web Junior")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")  
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#zip", "1011")
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-6 > div > div.v-input__control > div.v-input__slot > div.v-select__slot > div.v-select__selections")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active")
        .pause(500)
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-3 > div > div.v-input__control > div.v-input__slot")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active") 
        .pause(500)
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "La calle2: es inválida, no puede estar vacía")
        .pause(2000)
    },

    'Mensaje de error al crear la oferta con dirección sin ciudad': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#descripcion","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#cargo", "Desarrollador Web Junior")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")  
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "")
        .setValue("#estado", "Distrito Capital")
        .setValue("#zip", "1011")
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-6 > div > div.v-input__control > div.v-input__slot > div.v-select__slot > div.v-select__selections")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active")
        .pause(500)
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-3 > div > div.v-input__control > div.v-input__slot")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active") 
        .pause(500)
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "La ciudad: es inválida, no puede estar vacía")
        .pause(2000)
    },

    'Mensaje de error al crear la oferta con dirección sin estado': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#descripcion","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#cargo", "Desarrollador Web Junior")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")  
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "")
        .setValue("#zip", "1011")
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-6 > div > div.v-input__control > div.v-input__slot > div.v-select__slot > div.v-select__selections")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active")
        .pause(500)
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-3 > div > div.v-input__control > div.v-input__slot")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active") 
        .pause(500)
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "El estado: es inválido, no puede estar vacío")
        .pause(2000)
    },

    'Mensaje de error al crear la oferta con dirección sin zip': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#descripcion","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#cargo", "Desarrollador Web Junior")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")  
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#zip", "")
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-6 > div > div.v-input__control > div.v-input__slot > div.v-select__slot > div.v-select__selections")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active")
        .pause(500)
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-3 > div > div.v-input__control > div.v-input__slot")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active") 
        .pause(500)
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "El zip: es inválido, no puede estar vacío")
        .pause(2000)     
    },
    'Creación de oferta': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#descripcion","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#cargo", "Desarrollador Web Junior")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")  
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#zip", "1011")
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-6 > div > div.v-input__control > div.v-input__slot > div.v-select__slot > div.v-select__selections")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active")
        .pause(500)
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-3 > div > div.v-input__control > div.v-input__slot")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active") 
        .pause(500)
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div > div > div.row.d-none.d-md-flex > div > div > div", "Oferta Creada Con éxito")
        .pause(2000)
    },

    'Consultar Ofertas': function(browser){
        browser.url("http://localhost:8087/oferta")
        .assert.containsText("#app > div.v-application--wrap > main > div > div > div > div > div > div > div.py-4.ma-sm-9.v-card.v-sheet.v-sheet--shaped.theme--light.elevation-4 > div.v-data-table.mt-5.mx-5.v-data-table--fixed-header.v-data-table--has-bottom.theme--light > div.v-data-table__wrapper > table > tbody > tr > td:nth-child(1)", "Desarrollador")
        .assert.containsText("#app > div.v-application--wrap > main > div > div > div > div > div > div > div.py-4.ma-sm-9.v-card.v-sheet.v-sheet--shaped.theme--light.elevation-4 > div.v-data-table.mt-5.mx-5.v-data-table--fixed-header.v-data-table--has-bottom.theme--light > div.v-data-table__wrapper > table > tbody > tr > td:nth-child(2)", "Se requiere de un desarrollador para realizar aplicaciones móviles")
        .assert.containsText("#app > div.v-application--wrap > main > div > div > div > div > div > div > div.py-4.ma-sm-9.v-card.v-sheet.v-sheet--shaped.theme--light.elevation-4 > div.v-data-table.mt-5.mx-5.v-data-table--fixed-header.v-data-table--has-bottom.theme--light > div.v-data-table__wrapper > table > tbody > tr > td:nth-child(4)", "2020-05-05")
        .assert.containsText("#app > div.v-application--wrap > main > div > div > div > div > div > div > div.py-4.ma-sm-9.v-card.v-sheet.v-sheet--shaped.theme--light.elevation-4 > div.v-data-table.mt-5.mx-5.v-data-table--fixed-header.v-data-table--has-bottom.theme--light > div.v-data-table__wrapper > table > tbody > tr > td:nth-child(5) > span", "€ 700 por semana")
        .assert.containsText("#app > div.v-application--wrap > main > div > div > div > div > div > div > div.py-4.ma-sm-9.v-card.v-sheet.v-sheet--shaped.theme--light.elevation-4 > div.v-data-table.mt-5.mx-5.v-data-table--fixed-header.v-data-table--has-bottom.theme--light > div.v-data-table__wrapper > table > tbody > tr > td:nth-child(3)", "Sin Definir")
        .pause(2000)
    },

    'Publicar Oferta': function(browser){
        browser.url("http://localhost:8087/oferta")
        .click("#app > div.v-application--wrap > main > div > div > div > div > div > div > div.py-4.ma-sm-9.v-card.v-sheet.v-sheet--shaped.theme--light.elevation-4 > div.v-data-table.mt-5.mx-5.v-data-table--fixed-header.v-data-table--has-bottom.theme--light > div.v-data-table__wrapper > table > tbody > tr > td:nth-child(6) > button")
        .assert.containsText("#app > div.v-application--wrap > main > div > div > div > div > div > div > div.v-snack.v-snack--active.v-snack--has-background.v-snack--top > div > div.v-snack__content", "Oferta publicada con éxito")
        .pause(2000)
    }
}