module.exports = {
    'Creación de oferta': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div:nth-child(1) > button")
        .setValue("#titulo", "Desarrollador")
        .setValue("#descripcion","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#cargo", "Desarrollador Web Junior")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")  
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#zip", "1011")
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-6 > div > div.v-input__control > div.v-input__slot > div.v-select__slot > div.v-select__selections")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active")
        .pause(500)
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-3 > div > div.v-input__control > div.v-input__slot")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active") 
        .pause(500)
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div:nth-child(1) > div.v-snack.v-snack--has-background.v-snack--top > div", "Oferta Creada Con éxito")
        .pause(4000)
    },

    'Mensaje de error al crear la oferta sin título': function (browser) {
        browser.url("http://localhost:8087/oferta")
        .click("#app > div > main > div > div > div > div > div > div:nth-child(1) > button")
        .setValue("#titulo", "")
        .setValue("#descripcion","Se requiere de un desarrollador para realizar aplicaciones móviles")
        .setValue("#cargo", "Desarrollador Web Junior")
        .setValue("#vacantes", "1")
        .setValue("#fechaPostulacion", "2020-05-05")
        .setValue("#duracion", "8")  
        .setValue("#monto", "700")
        .setValue("#calle1", "Principal")
        .setValue("#calle2", "Oeste")
        .setValue("#ciudad", "Caracas")
        .setValue("#estado", "Distrito Capital")
        .setValue("#zip", "1011")
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-6 > div > div.v-input__control > div.v-input__slot > div.v-select__slot > div.v-select__selections")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active")
        .pause(500)
        .click("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__text > div:nth-child(7) > div.mt-0.pt-0.col.col-3 > div > div.v-input__control > div.v-input__slot")
        .pause(500)
        .click("#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active") 
        .pause(500)
        .assert.containsText("#tituloDatos", "Datos de la oferta")
        .assert.containsText("#app > div.v-dialog__content.v-dialog__content--active > div > div > div.v-card__subtitle.title.ml-2.mt-2.pb-1", "Datos de la oferta")
        .click("#crearOferta")
        .assert.title("hexawork-vue")
        .assert.containsText("#app > div > main > div > div > div > div > div > div:nth-child(1) > div.v-snack.v-snack--has-background.v-snack--top > div", "El titulo: \"\" es inválido, el título no puede estar vacío")
        .pause(4000)
    }
}